// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZIYLoeTpeonqvO0U-A6ATa_8pPu-7us',
    appId: '1:354479704196:android:ac99e996f0111943535ad1',
    messagingSenderId: '354479704196',
    projectId: 'evaranshark-test-apps',
    storageBucket: 'evaranshark-test-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqHRARBw8axpQC3yUA7GxGdxrzCtrlj4',
    appId: '1:354479704196:ios:3995e0ad895dcd14535ad1',
    messagingSenderId: '354479704196',
    projectId: 'evaranshark-test-apps',
    storageBucket: 'evaranshark-test-apps.appspot.com',
    androidClientId: '354479704196-0vmf63julk6c3aae501aktt0paemjole.apps.googleusercontent.com',
    iosClientId: '354479704196-mh0jknkefhts3iglejseah15obs9rh6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled54',
  );
}
